AttendanceSystemFinal/AttendanceSystemFinal/Controllers/securityController.cs
using AttendanceSystemFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AttendanceSystemFinal.Controllers
{
    [Authorize(Roles = "Secureity")]
    public class securityController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            List<Department> department = db.Departments.ToList<Department>();
            ViewBag.department = new SelectList(department, "DeptNo", "DeptName");
            return View();
        }

        public ActionResult dropdownone()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem() { Text = "choose", Value = "1" };
            SelectListItem item2 = new SelectListItem() { Text = "Attande", Value = "2" };
            SelectListItem item3 = new SelectListItem() { Text = "Exit", Value = "3" };
            items.Add(item1);
            items.Add(item2);
            items.Add(item3);
            ViewBag.items = items;
            return View();
        }
        public ActionResult getstudent(int id)
        {

            List<Student> students = db.Students.ToList().FindAll(a => a.DeptNo == id && a.IsAttend == false);
            List<Student> std = new List<Student>();

           
            foreach (var item in students)
            {

                std.Add(item);
            }

            return PartialView(std);
        }

        public ActionResult copy(int id)
        {

           
            Attendance student = new Attendance();


            Student std = db.Students.FirstOrDefault(a => a.stdId == id);
            std.IsAttend = true;
            student.stdId = std.stdId;
         
            student.date = DateTime.Now;
           
            student.attTime = DateTimeOffset.Now.TimeOfDay;

            db.attendances.Add(student);
            db.SaveChanges();

            return RedirectToAction("index");
        }
    }







}

AttendanceSystemFinal/AttendanceSystemFinal/Views/security/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mb-4">
    <div class="card-body">
        @Html.Label("Department name", new { @class = "lg mb-1" })

        @Html.DropDownList("department", ViewBag.department as SelectList, "--select Department--", new { @class = "btn btn-danger dropdown-toggle" })
       </div>
    </div>
        
        <div id="div1">



        </div>
        @section scripts{


            <script>
                $("#department").on("change", a => {

                    //  alert($("#department").val());
                    var id = $("#department").val();

                    $("#div1").load("/security/getstudent/" + id);

                })


            </script>

        }

AttendanceSystemFinal/AttendanceSystemFinal/Views/security/display.cshtml
@model IEnumerable<AttendanceSystemFinal.Models.Student>
@{
    ViewBag.Title = "display";
}

<h2>display</h2>



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <table>
        <thead>
            <tr>
                <th>id</th>
                <th>name</th>
                <th>age</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.stdId</td>
                    <td>@item.stdName</td>
                    <td>@item.DeptNo</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

AttendanceSystemFinal/AttendanceSystemFinal/Views/security/dropdownone.cshtml
@{
    ViewBag.Title = "dropdownone";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="layoutSidenav_content">
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Take Attendance</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/Home/index">Home</a></li>
            <li class="breadcrumb-item active">Take Attendance</li>
        </ol>
        <div class="card mb-4">
            <div class="card-body">

                @Html.Label("Choose Attend or Exit", new { @class = "lg mb-1" })

                @Html.DropDownList("items", null, null, new { @class = "btn btn-danger dropdown-toggle" })
                <div id="div1">



                </div>

            </div>

        </div>
    </div>
</main>
    </div>
  



@section scripts{


    <script>
        $("#items").on("change", a => {

            //  alert($("#department").val());
            var id = $("#items").val();
            if (id == 2) {
                $("#div1").load("/security/index/");
            }
            else if (id == 3) {
                $("#div1").load("/Exit/index");
            }

        })


    </script>

}

AttendanceSystemFinal/AttendanceSystemFinal/Views/security/getstudent.cshtml
@model List<AttendanceSystemFinal.Models.Student>

<div class="container-fluid">
<div class="card mb-4">
    <div class="card-header"><i class="fas fa-table mr-1"></i>All Students</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable"  cellspacing="0">
                <thead>
                    <tr>
    
                        <th>student name</th>
                        <th>student state</th>
                        
                    </tr>
                </thead>
                <tbody>
             @foreach (var item in Model)
            {


                        <tr>
                            <td>@item.stdName</td>
                            <td>@Html.ActionLink("attend", "copy", "security", new { Id = item.stdId }, new { @class = "btn btn-success" })</td>
                        </tr>

         }
                </tbody>
            </table>

        </div>
    </div>
</div>
    </div>

   